import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import Loader from "../components/Loader";
import ContextProvider from "@/providers/ContextProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-[#fefffe]">
        <ContextProvider>
          <ReactQueryProvider>
            <main>
              <Loader />
              {children}
            </main>
          </ReactQueryProvider>
            <ToastContainer />
        </ContextProvider>
      </body>
    </html>
  );
}
