import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import Loader from "../components/Loader";
import ContextProvider from "@/providers/ContextProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import SessionWrapper from "@/providers/SessionWrapper";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "MentorLand",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={`${poppins.className} text-[#fefffe]`}>
          <ContextProvider>
            <ReactQueryProvider>
              <main>
                <Loader />
                {children}
              </main>
            </ReactQueryProvider>
            <ToastContainer />
          </ContextProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
